services:
  mysql:
    image: mysql:8.0
    container_name: littleescape-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: littleescape
      MYSQL_USER: ezra
      MYSQL_PASSWORD: ljh1419*
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
